modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/DarkPred/NoCreativeDrift/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL = "https://www.curseforge.com/minecraft/mc-mods/nocreativedrift"
logoFile = "logo.png"
authors = "${mod_author}" #optional
description = '''${mod_description}'''

[[dependencies.${ mod_id }]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version_range_lower}, ${minecraft_version_range_upper})"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "simplyjetpacks"
mandatory = false
versionRange = "[2.10, 2.11)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "ironjetpacks"
mandatory = false
versionRange = "[7, 8)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "simplyjetpacks"
mandatory = false
versionRange = "[2.9, 2.10)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "ironjetpacks"
mandatory = false
versionRange = "[6, 7)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "mekanism"
mandatory = false
versionRange = "[10.3, 10.4)"
ordering = "NONE"
side = "BOTH"
