modLoader = "javafml"
loaderVersion = "${loader_version}"
license = "${mod_license}"
#issueTrackerURL="https://github.com/DarkPred/Some-Mod/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL = "https://www.curseforge.com/minecraft/mc-mods/some-mod"
logoFile="logo.png"
authors = "${mod_author}" #optional
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "simplyjetpacks"
mandatory = false
versionRange = "[2.8, 2.9)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "ironjetpacks"
mandatory = false
versionRange = "[5, 6)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "mekanism"
mandatory = false
versionRange = "[10.2, 10.3)"
ordering = "NONE"
side = "BOTH"
