modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/DarkPred/NoCreativeDrift/issues"

[[mods]]
modId="nocreativedrift"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/nocreativedrift"
logoFile="logo.png"
authors="DarkPred"
displayTest="NONE"
description='''
Stops the player from drifting after they stop flying.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.nocreativedrift]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nocreativedrift]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nocreativedrift]]
    modId="controllable"
    mandatory=false
    versionRange="[0.20.0, 0.21.0)"
    ordering="AFTER"
    side="BOTH"