modLoader="javafml"
loaderVersion="[32,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/DarkPred/NoCreativeDrift/issues"

[[mods]]
modId="nocreativedrift"
version="${file.jarVersion}"
displayName="NoCreativeDrift"
displayURL="https://www.curseforge.com/minecraft/mc-mods/nocreativedrift"
authors="DarkPred"
description='''
Stops the player from drifting after they stop moving in creative flying mode.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.nocreativedrift]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.nocreativedrift]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nocreativedrift]]
    modId="simplyjetpacks"
    mandatory=false
    versionRange="[1.16.3, 1.17)"
    ordering="AFTER"
    side="BOTH"