modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/DarkPred/NoCreativeDrift/issues"

[[mods]]
modId="nocreativedrift"
version="${version}"
displayName="NoCreativeDrift"
displayURL="https://www.curseforge.com/minecraft/mc-mods/nocreativedrift"
logoFile="logo.png"
authors="DarkPred"
description='''
Stops the player from drifting after they stop flying.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.nocreativedrift]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.nocreativedrift]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"
[[dependencies.nocreativedrift]]
modId="ironjetpacks"
mandatory=false
versionRange="[5.1.1, 6.0.0)"
ordering="AFTER"
side="BOTH"
[[dependencies.nocreativedrift]]
modId="mekanism"
mandatory=false
versionRange="[10.2.4, 10.3.0)"
ordering="AFTER"
side="BOTH"
[[dependencies.nocreativedrift]]
modId="simplyjetpacks"
mandatory=false
versionRange="[1.18.2-2.8.0.1, 1.19)"
ordering="AFTER"
side="BOTH"
[[dependencies.nocreativedrift]]
modId="controllable"
mandatory=false
versionRange="[0.16.0, 0.17.0)"
ordering="AFTER"
side="BOTH"