modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/DarkPred/NoCreativeDrift/issues"

[[mods]]
modId="nocreativedrift"
version="${file.jarVersion}"
displayName="NoCreativeDrift"
displayURL="https://www.curseforge.com/minecraft/mc-mods/nocreativedrift"
authors="DarkPred"
description='''
Stops the player from drifting after they stop moving in creative flying mode.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.nocreativedrift]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nocreativedrift]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.nocreativedrift]]
    modId="simplyjetpacks"
    mandatory=false
    versionRange="[1.15.2]"
    ordering="AFTER"
    side="BOTH"
    