modLoader="javafml"
loaderVersion="[41,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/DarkPred/NoCreativeDrift/issues"

[[mods]]
modId="nocreativedrift"
version="${version}"
displayName="NoCreativeDrift"
displayURL="https://www.curseforge.com/minecraft/mc-mods/nocreativedrift"
logoFile="logo.png"
authors="DarkPred"
description='''
Stops the player from drifting after they stop flying.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.nocreativedrift]]
modId="forge"
mandatory=true
versionRange="[41,)"
ordering="NONE"
side="BOTH"

[[dependencies.nocreativedrift]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.nocreativedrift]]
modId="ironjetpacks"
mandatory=false
versionRange="[6.0.0, 7.0.0)"
ordering="AFTER"
side="BOTH"
[[dependencies.nocreativedrift]]
modId="mekanism"
mandatory=false
versionRange="[10.3.0, 10.4.0)"
ordering="AFTER"
side="BOTH"