modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/DarkPred/NoCreativeDrift/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL = "https://www.curseforge.com/minecraft/mc-mods/nocreativedrift"
logoFile = "logo.png"
authors = "${mod_author}" #optional
description = '''${mod_description}'''
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "mekanism"
type = "optional"
versionRange = "[10.6, 10.8)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "ironjetpacks"
type = "optional"
versionRange = "[8, 9)"
ordering = "NONE"
side = "BOTH"

